Skip target-arch when it is empty string

diff --git a/.github/workflows/build-package-from-git-repository.yml b/.github/workflows/build-package-from-git-repository.yml
--- a/.github/workflows/build-package-from-git-repository.yml
+++ b/.github/workflows/build-package-from-git-repository.yml
@@ -82,8 +82,11 @@ jobs:
                   fi
                   ;;
                 *)
-                  echo "::error::Unsupported target arch $target_arch."
-                  exit 1
+                  if [[ -n "$target_arch" ]]
+                  then
+                    echo "::error::Unsupported target arch $target_arch."
+                    exit 1
+                  fi
                   ;;
               esac
             done <<< '${{ inputs.target-archs }}'
